# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://idia.photo/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: idia.photo
# Description of the Site
description: Jesteśmy Idia. 
# URL of Image of the Site
site-image: /assets/images/idia-logo.jpg
# Keywords of the Site
site-keywords: Towarzystwo Fotograficzne, Idia, Fotografia, Photography, Grupa inspirująca
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/jestesmy-idia.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: krzysztof@kwiatkowscy.com
facebook_url: https://www.facebook.com/profile.php?id=100093358247323
twitter_username:
instagram_username: idia.photo
linkedin_username:
github_username:
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:

# Name of the Author
author-name: idia.photo
# URL for the Image of the Author
author-image: /assets/images/idia-logo.jpg
# 60 Words About the Author
author-about: Towarzystwo Fotograficzne IDIA powstało z głębokiego szacunku do fotografii. Jako aktywni artyści jesteśmy żywo zainteresowani tą formą twórczego spojrzenia na rzeczywistość. Pozostałe, niefotograficzne kwestie, są nam obce. Jako grupa realizujemy konkretne cele artystyczne, indywidualnie lub wspólnie. Jesteśmy zatem jednością, która szanuje indywidualizm oraz inspiruje do samodzielnych poszukiwań artystycznych. Jako grupa pozostajemy otwarci na współpracę z innymi stowarzyszeniami artystycznymi – w kraju i na Świecie. Fotografia powinna łączyć, a miłość do niej – zbliżać. A jeśli mamy się różnić to tylko (parafrazując słowa Cypriana Norwida) pięknie oraz mocno.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.facebook.com/profile.php?id=100093358247323

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
